/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abesi
 */
public class ViewAllRecord extends javax.swing.JFrame {
DefaultTableModel model;
    public ViewAllRecord() {
        initComponents();
        setIssueBookDetailsTable();
    /**
     * Creates new form AllViewrecord
     */}
    
    public void setIssueBookDetailsToTable(){
       
        try{ 
            Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/system", 
            "root", 
            "200651802829@Dew"
        );
            Statement st = con.createStatement();
         ResultSet  rs= st.executeQuery("select * from issue_book_details");
                  while(rs.next()){
             String id =rs.getString("book_id");
             String bookName =rs.getString("book_name");
             String studentName =rs.getString("Student_id");
             String statuse =rs.getString("statuse");
             
             Object[] obj  = {id,bookName,studentName,statuse};
             model = (DefaultTableModel)  jTable1.getModel();
             model.addRow(obj);      
              }
        }catch(Exception e){
            e.printStackTrace();
        }
    }  
       public void setIssueBookDetailsTable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
    }
       public void clearTable(){
           DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
           model.setRowCount(0);
       }
       
    /**   public void search(){
           Date  uFromDate = date_fromDate.getDatoFecha();
           Date  uToDate =date_toDate.getDatoFecha();
           
          long l1 = uFromDate.getTime();
           long l2 =uToDate.getTime();
           java.sql.Date fromDate =new java.sql.Date(11);
           java.sql.Date toDate= new java.sql.Date(12);
           try{
               Connection con =DBConnection.getConnection();
               String sql ="Select * from issue_book_details where issue_date  BETWEEN ? to ?";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setDate(1,fromDate);
              pst.setDate(2,toDate);
              
               ResultSet rs = pst.executeQuery();
               if(rs.next()==false){
                   JOptionPane.showMessageDialog(this,"No Record Found");
}else{
                   
               
               while(rs.next()){
             String id =rs.getString("book_id");
             String bookName =rs.getString("book_name");
             String studentName =rs.getString("Student_id");
             String statuse =rs.getString("statuse");
             
             Object[] obj  = {id,bookName,studentName,issueDate,dueDate,statuse};
             model = (DefaultTableModel)tbl_issueBookDetails.getModel();
             model.addRow(obj);      
              }
               }
           }catch(Exception e){
               e.printStackTrace();
           }
       }  **/ 
 
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        date_fromDate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        date_toDate = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_table = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1480, 280));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\abesi\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagementSystem_new\\src\\resources\\icons8_Literature_100px_1.png")); // NOI18N
        jLabel1.setText("View All Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 360, 110));
        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 380, 10));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle1.setText("SEARCH");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 150, 210, 50));

        date_fromDate.setBackground(new java.awt.Color(0, 204, 204));
        date_fromDate.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        date_fromDate.setForeground(new java.awt.Color(255, 255, 255));
        date_fromDate.setToolTipText("");
        date_fromDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        date_fromDate.setName(""); // NOI18N
        date_fromDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_fromDateFocusLost(evt);
            }
        });
        date_fromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_fromDateActionPerformed(evt);
            }
        });
        jPanel1.add(date_fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, 40));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Issue Date :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, 30));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Issue Date:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 130, 30));

        date_toDate.setBackground(new java.awt.Color(0, 153, 153));
        date_toDate.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        date_toDate.setForeground(new java.awt.Color(255, 255, 255));
        date_toDate.setToolTipText("");
        date_toDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        date_toDate.setName(""); // NOI18N
        date_toDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_toDateFocusLost(evt);
            }
        });
        date_toDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_toDateActionPerformed(evt);
            }
        });
        jPanel1.add(date_toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 230, 40));

        jPanel4.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setBackground(new java.awt.Color(0, 0, 204));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 30, 30));

        jLabel3.setBackground(new java.awt.Color(204, 0, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\abesi\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagementSystem_new\\src\\resources\\icons8_Rewind_48px.png")); // NOI18N
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 102, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 200));

        panel_table.setBackground(new java.awt.Color(255, 255, 255));
        panel_table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abesi\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagementSystem_new\\src\\resources\\library-3.png.png")); // NOI18N
        panel_table.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 800, 630));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        panel_table.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 680, 360));

        jTable1.setBackground(new java.awt.Color(255, 0, 0));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Book Name", "Student Name", "Issue  Date", "Due Date", "statuse"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        panel_table.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 290));

        getContentPane().add(panel_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1520, 680));

        setSize(new java.awt.Dimension(1535, 865));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void date_fromDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_fromDateFocusLost

    }//GEN-LAST:event_date_fromDateFocusLost

    private void date_fromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_fromDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_fromDateActionPerformed

    private void date_toDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_toDateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_date_toDateFocusLost

    private void date_toDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_toDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_toDateActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        HomePage home =new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
         HomePage home =new HomePage();
       home.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed

     //   clearTable();
     //   search();      

    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date_fromDate;
    private javax.swing.JTextField date_toDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_table;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    // End of variables declaration//GEN-END:variables
}
